USE 02_db_stg_compliance_hub_ticketing;

ALTER TABLE ticketing_configs
ADD COLUMN schedule_mode VARCHAR(20) NOT NULL DEFAULT 'OFFICE_HOURS',
ADD COLUMN office_clockin TIME NOT NULL DEFAULT '08:00:00',
ADD COLUMN office_clockout TIME NOT NULL DEFAULT '17:00:00',
ADD COLUMN cww_clockin_start TIME NOT NULL DEFAULT '07:00:00',
ADD COLUMN cww_clockin_end TIME NOT NULL DEFAULT '08:00:00',
ADD COLUMN cww_clockout_start TIME NOT NULL DEFAULT '18:00:00',
ADD COLUMN cww_clockout_end TIME NOT NULL DEFAULT '19:00:00',
ADD COLUMN is_flag_ceremony_paused BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE tickets
ADD COLUMN is_sla_waiting BOOLEAN NOT NULL DEFAULT 0;

